services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'main_db'
      MYSQL_PASSWORD: '123'
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  pg_data:
  node_modules:
  mysql_data:
